name: 'dns_cf_push'

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:  # 新增这行，明确支持手动触发
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: 'Install dependencies'
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'run dnscf'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_DNS_NAME: ${{ vars.CF_DNS_NAME }}  # 修改此处，使用 vars 引用变量
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python dnscf.py
